a=int(input("valoarea primului numar:"))
b=int(input("valoarea al doilea numar:"))
c=int(input("valoare al treilea numar:"))
print(a, "+", b, "=", a+b)
print(a, "+", c, "=", a+c)
print(b, "+", c, "=", b+c)
